# This container is specific to the application.
# It contains configuration and data for other containers.
data:
    build: ./docker
    volumes:
        - {your_app_path}:/srv
        - {your_app_path}/docker/conf/nginx_vhost.conf:/etc/nginx/sites-enabled/my_app.conf
        - {your_app_path}/.bashrc.docker:/home/developer/.bashrc
        - {your_app_path}/.ssh:/home/developer/.ssh

webserver:
    build: ./docker/docker-images/nginx
    ports:
        - '80:80'
    volumes_from:
        - data
    links:
        - appserver

appserver:
    build: ./docker/docker-images/php
    ports:
        - '9000:9000'
    volumes_from:
        - data
    links:
        - database
        - memorycache
        - elasticsearch
        - mailer
    environment:
        USERNAME: {your_unix_local_username}
        UNIX_UID: {your_unix_local_uid}

database:
    build: ./docker/docker-images/postgres
    ports:
        - '5432:5432'
    volumes_from:
        - data
    environment:
        POSTGRES_DB: {your_db_name}
        POSTGRES_USER: {your_db_user}
        POSTGRES_PASSWORD: {your_db_password}

mailer:
    build: ./docker/docker-images/mailcatcher
    ports:
        - '1080:1080'
        - '1025:1025'

memorycache:
    build: ./docker/docker-images/memcached
    ports:
        - '11211:11211'

elasticsearch:
    build: ./docker/docker-images/elasticsearch
    volumes_from:
        - data
    ports:
        - "9200:9200"
        - "9300:9300"
